In [2]:
import numpy as np

In [4]:
five_data = np.genfromtxt('five.txt', dtype = 'int16')
five_data

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]], dtype=int16)

In [8]:
ones_data = np.ones((5,5), dtype='int32')
ones_data

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
dot_data = np.dot(five_data, ones_data)
dot_data

array([[ 5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10],
       [15, 15, 15, 15, 15],
       [20, 20, 20, 20, 20],
       [25, 25, 25, 25, 25]])

In [11]:
matmul_data = np.matmul(five_data, ones_data)
matmul_data

array([[ 5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10],
       [15, 15, 15, 15, 15],
       [20, 20, 20, 20, 20],
       [25, 25, 25, 25, 25]])

In [12]:
x_data = five_data @ ones_data
x_data

array([[ 5,  5,  5,  5,  5],
       [10, 10, 10, 10, 10],
       [15, 15, 15, 15, 15],
       [20, 20, 20, 20, 20],
       [25, 25, 25, 25, 25]])

In [13]:
y_data = five_data * ones_data
y_data

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [14]:
np.save('dot_data', dot_data)

In [15]:
np.savetxt('dot_data.txt', dot_data)